### ISSUE TITLE
Http 500: No devices found to debug. Please ensure that a device is connected and awake and retry

### ISSUE THREAD

**Issue by stefdelec** [Microsoft/remotebuild#15]
I got this error:
Http 500: No devices found to debug. Please ensure that a device is connected and awake and retry

Don't no what to do.

Thanks,

Stéphane.

**Comment by MSLaguana** [comment]
Have you plugged your iOS device into the mac running remotebuild? If so, what happens if you run `ideviceinfo` on that machine?

**Comment by stefdelec** [comment]
In the Mac Terminal ? (I try it tomorrow at work).

**Comment by MSLaguana** [comment]
Yes, in a terminal.

If you get an error that `ideviceinfo` isn't a known command, then the error may be because you haven't installed some third party tools that we require to interact with devices. In that case, you will need to make sure you have homebrew installed and run `brew update && brew install ios-webkit-debug-proxy ideviceinstaller` (and if you plan to work with iOS 10 devices, `brew upgrade libimobiledevice --HEAD`).

**Comment by stefdelec** [comment]
```
WAxxxx:~ user1$ brew update && brew install ios-webkit-debug-proxy ideviceinstaller

Already up-to-date.

You can link formula with `brew link ios-webkit-debug-proxy`

Warning: ios-webkit-debug-proxy-1.7 already installed, it's just not linked

Error: You must `brew link usbmuxd` before ideviceinstaller can be installed

WABEAPAR09-0508:~ sdelecroix$ brew link usbmuxd

Linking /usr/local/Cellar/usbmuxd/1.0.10_1... 

Error: Could not symlink bin/iproxy

Target /usr/local/bin/iproxy

is a symlink belonging to usbmuxd. You can unlink it:

  brew unlink usbmuxd



To force the link and overwrite all conflicting files:

  brew link --overwrite usbmuxd



To list all files that would be deleted:

  brew link --overwrite --dry-run usbmuxd
```

I ve got this vicious circle. Whatever option I choose i stumble upon this error...  What should I do?

**Comment by MSLaguana** [comment]
I'm going to close this out for now. If you are still running into this issue, feel free to reopen.
